### ISSUE TITLE
Codenamesgreen no longer working at hosted site

### ISSUE THREAD

**Issue by Alecat** [jbowens/codenamesgreen#8]
Thank you for Codenames Green! My partner and I have really enjoyed scratching the codenames itch with just two players.

As of yesterday we have had trouble using the website for games.

When joining a room the spinner remains indefinitely and the console shows this error:

`Uncaught TypeError: Cannot read property 'storeCache' of undefined`

After a while some CORS errors also show:

`Access to XMLHttpRequest at 'https://api.codenamesgreen.com/new-game' from origin 'https://www.codenamesgreen.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

**Comment by Alecat** [comment]
May be the same issue as https://github.com/jbowens/codenamesgreen/issues/7

**Comment by jbowens** [comment]
Sorry about that, should be ok now.

**Comment by Alecat** [comment]
Thank you! Looking forward to more games :)
